<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pole">
  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:property name="pole_l" value="3.3528" />
  <xacro:property name="pole_r" value="0.035" />
  
  <xacro:property name="cartesian_joint_effort_main" value="1"/>
  <xacro:property name="spherical_joint_effort_main" value="10000"/>

  <xacro:property name="num_cylindrical_links" value="2" />

  <xacro:if value="${num_cylindrical_links % 2 == 0}">
    <xacro:property name="num_spherical_joints" value="${num_cylindrical_links}" />
  </xacro:if>
  <xacro:unless value="${num_cylindrical_links % 2 == 0}">
    <xacro:property name="num_spherical_joints" value="${num_cylindrical_links - 1}" />
  </xacro:unless>

  <xacro:property name="total_bend_limit" value="${PI}" />

  <!-- <xacro:property name="spherical_joint_limit" value="${total_bend_limit/num_spherical_joints}"/> -->
  <xacro:property name="spherical_joint_limit" value="${total_bend_limit/(num_spherical_joints-1)}"/>
  <xacro:property name="spherical_joint_effort" value="1"/>

  <!-- Link Lengths -->
  <xacro:property name="length" value="${pole_l/num_cylindrical_links}"/>
  
  <!-- Include statements for macros -->
  <xacro:include filename="cartesian_joint_macro.xacro"/>
  <xacro:include filename="spherical_joint_macro.xacro"/>
  <xacro:include filename="cylindrical_link_macro.xacro"/>

  <!-- Base link -->
  <link name="base_link"/>

  <!-- Instantiate the MAIN Cartesian Joint Macro -->
  <xacro:cartesian_joint prefix="cartesian" lower_limit="-3" upper_limit="3" effort="${cartesian_joint_effort_main}" velocity="1.5"/>

  <!-- Instantiate the MAIN Spherical Joint Macro -->
  <xacro:spherical_joint prefix="spherical" lower_limit="-${PI}" upper_limit="${PI}" effort="${spherical_joint_effort_main}" velocity="${PI/2}"/>

  <!-- Tool link is where the tip of the combined cartesian + spherical joints is at -->
  <link name="tool0"/>

  <!-- Connections between components -->
  
  <!-- Connect Cartesian joint system to the base -->
  <joint name="base_to_cartesian" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/> 
    <parent link="base_link"/>
    <child link="cartesian_parent_link"/>
  </joint>

  <!-- Connect spherical joint to the top of the cartesian joint -->
  <joint name="cartesian_to_spherical" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/> 
    <parent link="cartesian_z_link"/>
    <child link="spherical_parent_link"/>
  </joint>

  <!-- Connect the tool link with the the tip of the combined cartesian + spherical joints -->
  <joint name="spherical_to_tool0" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/> 
    <parent link="spherical_roll_link"/>
    <child link="tool0"/>
  </joint>


  <!-- +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

  <!-- Add a link from tool0 to left -->
  <link name="link_left_1_root">
    <visual>
        <geometry>
            <cylinder length="${length}" radius="${pole_r}"/>
        </geometry>
        <origin xyz="0 0 ${length / 2}" rpy="0 0 0"/>
        <material name="teal"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${length}" radius="${pole_r}"/>
        </geometry>
        <origin xyz="0 0 ${length / 2}" rpy="0 0 0"/>
    </collision>
  </link>

  <!-- Connect tool0 to the root of left link -->
  <joint name="tool0_to_link_left_1_root" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="tool0"/>
    <child link="link_left_1_root"/>
  </joint>

  <!-- Define the tip of the left link -->
  <link name="link_left_1_tip"/>

  <!-- Connect the tip to the root with a fixed joint -->
  <joint name="joint_link_left_1_root_to_tip" type="fixed">
    <origin xyz="0 0 ${length}" rpy="0 0 0"/>
    <parent link="link_left_1_root"/>
    <child link="link_left_1_tip"/>
  </joint>

  <!-- Define another link to come back to the root -->
  <link name="link_left_1_root_back"/>

  <!-- Connect the tip to the root with a fixed joint -->
  <joint name="joint_link_left_1_tip_to_root_back" type="fixed">
    <origin xyz="0 0 -${length}" rpy="0 0 0"/>
    <parent link="link_left_1_tip"/>
    <child link="link_left_1_root_back"/>
  </joint>

  <!-- Define the spherical joint -->
  
  <link name="link_yaw"/>

  <!-- Revolute joint around Z-axis -->
  <joint name="joint_yaw" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="link_left_1_root_back"/>
      <child link="link_yaw"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${spherical_joint_limit/2.0}" upper="${spherical_joint_limit/2.0}" effort="${spherical_joint_effort}" velocity="${PI/2}"/>
  </joint>

  <link name="link_pitch"/>

  <!-- Revolute joint around Y-axis -->
  <joint name="joint_pitch" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="link_yaw"/>
      <child link="link_pitch"/>
      <axis xyz="0 1 0"/>
      <limit lower="-${spherical_joint_limit/2.0}" upper="${spherical_joint_limit/2.0}" effort="${spherical_joint_effort}" velocity="${PI/2}"/>
  </joint>

  <!-- Add a link from the root back to right -->
  <link name="link_right_1_root">
    <visual>
        <geometry>
            <cylinder length="${length}" radius="${pole_r}"/>
        </geometry>
        <origin xyz="0 0 -${length / 2}" rpy="0 0 0"/>
        <material name="teal"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${length}" radius="${pole_r}"/>
        </geometry>
        <origin xyz="0 0 -${length / 2}" rpy="0 0 0"/>
    </collision>
  </link>

  <!-- Connect the root back to the right link with a revolute joint from the x axis-->
  <joint name="joint_link_left_1_root_back_to_right_1_root" type="revolute">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="link_pitch"/>
    <child link="link_right_1_root"/>
    <axis xyz="1 0 0"/>
    <limit lower="-${spherical_joint_limit/2.0}" upper="${spherical_joint_limit/2.0}" effort="${spherical_joint_effort}" velocity="${PI/2}"/>
  </joint>


















  <!-- Define the tip of the right link -->
  <link name="link_right_1_tip"/>

  <!-- Connect the tip to the root with a fixed joint -->
  <joint name="joint_link_right_1_root_to_tip" type="fixed">
    <origin xyz="0 0 -${length}" rpy="0 0 0"/>
    <parent link="link_right_1_root"/>
    <child link="link_right_1_tip"/>
  </joint>

  <!-- Define another link to come back to the root -->
  <link name="link_right_1_root_back"/>
  
  <!-- Connect the tip to the root with a fixed joint -->
  <joint name="joint_link_right_1_tip_to_root_back" type="fixed">
    <origin xyz="0 0 ${length}" rpy="0 0 0"/>
    <parent link="link_right_1_tip"/>
    <child link="link_right_1_root_back"/>
  </joint>

  <!-- Define final tool as tool1 link -->
  <link name="tool1"/>

  <!-- Connect the right root back to the tool1 link -->
  <joint name="joint_link_right_1_root_back_to_tool1" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="link_right_1_root_back"/>
    <child link="tool1"/>
  </joint>

</robot>
