<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pole">
  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:property name="pole_l" value="3.3528" />
  <xacro:property name="pole_r" value="0.035" />
  <xacro:property name="pole_num_segments" value="40" />
  <xacro:property name="num_cylindrical_links" value="1" />
  
  <!-- Include statements for macros -->
  <xacro:include filename="cartesian_joint_macro.xacro"/>
  <xacro:include filename="spherical_joint_macro.xacro"/>
  <xacro:include filename="cylindrical_link_macro.xacro"/>

  <!-- Base link -->
  <link name="base_link"/>

  <!-- Instantiate the MAIN Cartesian Joint Macro -->
  <xacro:cartesian_joint prefix="cartesian" lower_limit="-3" upper_limit="3" effort="10000" velocity="1.5"/>

  <!-- Instantiate the MAIN Spherical Joint Macro -->
  <xacro:spherical_joint prefix="spherical" lower_limit="-${PI}" upper_limit="${PI}" effort="1" velocity="${PI/2}"/>

  <!-- Tool link is where the tip of the combined cartesian + spherical joints is at -->
  <link name="tool0"/>

  <!-- Connections between components -->
  
  <!-- Connect Cartesian joint system to the base -->
  <joint name="base_to_cartesian" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/> 
    <parent link="base_link"/>
    <child link="cartesian_parent_link"/>
  </joint>

  <!-- Connect spherical joint to the top of the cartesian joint -->
  <joint name="cartesian_to_spherical" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/> 
    <parent link="cartesian_z_link"/>
    <child link="spherical_parent_link"/>
  </joint>

  <!-- Connect the tool link with the the tip of the combined cartesian + spherical joints -->
  <joint name="spherical_to_tool0" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/> 
    <parent link="spherical_roll_link"/>
    <child link="tool0"/>
  </joint>


  <!-- Instantiate the Cylindrical Link Macros -->
  <xacro:cylindrical_link prefix="cylindrical" length="${pole_l/num_cylindrical_links}" diameter="${2*pole_r}"/>

  <!-- Connect Cylindrical Link to the top of the tool -->
  <joint name="tool0_to_cylindrical" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="tool0"/>
    <child link="cylindrical_center_link"/>
  </joint>

  <!-- Create robot holding points as fixed links -->

  <xacro:macro name="add_pole_holder_link" params="segment_id num_segments pole_length">
    <link name="pole_holder_link_${segment_id}"></link>
    
    <joint name="pole_holder_fixed_joint_${segment_id}" type="fixed">
      <parent link="tool0"/>
      <child link="pole_holder_link_${segment_id}"/>
      <origin xyz="0 0 ${-pole_length/2 + (pole_length * (1 + 2 * segment_id)) / (2 * num_segments)}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:add_pole_holder_link segment_id="5" num_segments="${pole_num_segments}" pole_length="${pole_l}"/>
  <xacro:add_pole_holder_link segment_id="34" num_segments="${pole_num_segments}" pole_length="${pole_l}"/>



</robot>
